// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"

func Graph(n int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Quadruplet</title><script src=\"https://go-echarts.github.io/go-echarts-assets/assets/echarts.min.js\"></script><script src=\"https://go-echarts.github.io/go-echarts-assets/assets/echarts@4.min.js\"></script><script src=\"https://go-echarts.github.io/go-echarts-assets/assets/echarts-gl.min.js\"></script><script src=\"https://go-echarts.github.io/go-echarts-assets/assets/themes/westeros.js\"></script><style>\n                #slider-container {\n                    position: fixed;\n                    left: 0;\n                    top: 0;\n                    width: 300px;\n                    padding: 20px;\n                    box-sizing: border-box;\n                    height: 100vh;\n                    overflow-y: auto;\n                    background-color: #f4f4f4;\n                }\n                .slider {\n                    margin: 10px 0;\n                }\n                .container {\n                    margin-top:30px;\n                    display: flex;\n                    justify-content: center;\n                    align-items: center;\n                }\n                .item {\n                    margin: auto;\n                }\n            </style></head><body><div id=\"slider-container\"><button id=\"DefaultConfig\">Default</button><br><form id=\"slider-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i := 0; i < n; i++ {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span>Leg ID ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", i))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/QuadrupotGraphPage.templ`, Line: 46, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" : </span><div class=\"slider\"><span id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("sliderValue%d", i*(n-1)+0)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">0</span> <input id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("slider%d", i*(n-1)+0)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" type=\"range\" min=\"-48\" max=\"48\" value=\"0\" class=\"slider-input\"></div><div class=\"slider\"><span id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("sliderValue%d", i*(n-1)+1)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">-90</span> <input id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("slider%d", i*(n-1)+1)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" type=\"range\" min=\"-200\" max=\"90\" value=\"-90\" class=\"slider-input\"></div><div class=\"slider\"><span id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("sliderValue%d", i*(n-1)+2)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">-90</span> <input id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("slider%d", i*(n-1)+2)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" type=\"range\" min=\"-156\" max=\"-48\" value=\"-90\" class=\"slider-input\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form></div><div class=\"container\"><div class=\"item\" id=\"quadruplet\" style=\"width: 900px; height: 500px; user-select: none; position: relative;\" _echarts_instance_=\"ec_1706227771081\"><div style=\"position: relative; width: 900px; height: 500px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;\"><canvas style=\"width: 900px; height: 500px; position: absolute; left: 0px; top: 0px;\" width=\"900\" height=\"500\"></canvas><canvas style=\"position: absolute; left: 0px; top: 0px; width: 900px; height: 500px; user-select: none; padding: 0px; margin: 0px; border-width: 0px;\" data-zr-dom-id=\"zr_0\" width=\"900\" height=\"500\"></canvas></div></div></div><script type=\"module\" src=\"/js/graph.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
